### PR TITLE
Update Constitution for 2017-2018

### PR DESCRIPTION
**Pull request by JohnLinahan**
I made changes of my influenced by different sources like WiCS and combined them with the changes that @kingsman142 made.

@kingsman142 original commits were moved to constitution_v1.1.

### CODE REVIEW

**Comment by timparenti** [comment]
@SPN11 I presume this merge means that the changes here have received "a simple majority vote of approval from the board and a two-thirds vote of approval from the body of active student members" in accordance with Article XXV of the [previous version](https://github.com/Pitt-CSC/Documents/blob/acb7a37bfe521cdd4e5bfed3bef5954d8c4181a4/Constitution.md)?  If not, can you clarify the nature of this change?

**Comment by JohnLinahan** [comment]
@timparenti There were a lot of changes in the new constitution requirements so we copied sections from the old constitution into a the new template. Looks like we missed the amendments section in the process.

**Comment by timparenti** [comment]
So has this been passed and approved, then?  Or is that still yet to happen?  (And if the latter, should this be on `proposed` instead of `master`?)

Just trying to understand the status.

**Comment by JohnLinahan** [comment]
The previous version is two years out of date if I recall correctly, many components don't accurately reflect the current state of the club, for instance, the committees and chair positions don't exist anymore.

As for passage and approval, its impossible for us to get a "two-thirds vote of approval from the body of active student members" as active members weren't kept track of all year by the previous board and assembling them together would be impossible given it being the Summer.

The changes were in `constitution_v2` until we merged them into `master`. `constitution_v2` was the `proposed` in this case.

**Comment by timparenti** [comment]
> many components don't accurately reflect the current state of the club, for instance, the committees and chair positions don't exist anymore.

That's a laudable reason to propose changes to a club constitution, especially with an organization this young which often has shifting needs.  As an alumnus who cares about what the CSC does at Pitt, I appreciate your efforts toward keeping this all in order, and I'm sure the current membership does as well.

> active members weren't kept track of all year by the previous board

Perhaps this should become enumerated as an explicit responsibility of a particular officer, then?

> assembling them together would be impossible given it being the Summer.

The solution to that isn't just plowing ahead with the changes anyway.  There's no provision in the previous document for amending without a vote.  It sounds like a list of active members needs to be established first thing in the fall, and this can't really be considered approved (as far as SORC is concerned) until a vote takes place (soon!) thereafter.  It's only due to the potential for confusion that I'd fairly strongly advise keeping this off `master` in the interim.

**Comment by JohnLinahan** [comment]
>Perhaps this should become enumerated as an explicit responsibility of a particular officer, then?
Another great revision we can make.

As far as SORC is concerned... actually, I would say that they aren't concerned. Other clubs' constitutions are outdated or don't fulfill the requirements and they haven't given any indication that they closely monitor club activities in the past.

Now I'm not trying to say that makes it okay for us to change the constitution because SORC doesn't care. I'm not saying that we should be able to do whatever we want because nobody will catch us. But as the SORC re-registration due date approaches we have to hand in a constitution. I deemed it better to hand in an new one, while technically illegitimate, than an outdated inaccurate one.

That begs the question of what our _real_ constitution is. It can't be the one on SORC because of the reasons above. Does that mean that its the one on `master` then? Maybe. So we _could_ revert and go back to a 'proposed' branch.

More importantly, how do the members feel about this? I would say the overwhelming majority don't know about or don't care about the constitution in the first place. But once again, their ignorance is not an excuse to change the constitution without their consent.

I understand the sentiment of trying to uphold the club's constitution. Hopefully with the intention of preventing some Machiavellian rogue from destroying what we've all worked so hard to build and maintain. Also, what good is a constitution if it is not upheld? The actions we supposedly take nullify it's existence. 
In my opinion, it's impractical to uphold the constitution at every turn for a student organization in a university. We are not a government or a nation so we should not act like one. I just don't think it matters that much. I don't think we should put so much thought and effort into something that doesn't actually affect the club. That being said, I will revert and we will continue to revise `constitution_v2`.

**Comment by timparenti** [comment]
It is undeniable that the needs of a student organization, especially a young one, change, and that the documents submitted to explain that shifting structure to any overseeing bodies (despite what little oversight they may provide) should strive to reflect current practice, both for their benefit and for the benefit of the institutional memory of the organization.  For those reasons, I doubt you'll have any trouble with the organization's support for these changes.  As for which copy is canonical, it only ever really matters in the case of disputes, anyway, which are hopefully rare to begin with, but I'd imagine if anything ever rose to SORC's level, they'd hew to their copy unless otherwise notified.

Anyway, thanks for your well-thought consideration on all of this.  Again, it's very much appreciated.

**Pull request merged**
